# Generated by Django 4.2.11 on 2024-04-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_category_is_active_category_priority_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountBySubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("subcategory", models.ManyToManyField(to="api.subcategory")),
            ],
        ),
    ]
