# Generated by Django 4.2.11 on 2024-04-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_discountbysubcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="subcategories",
            field=models.ManyToManyField(blank=True, to="api.subcategory"),
        ),
        migrations.DeleteModel(
            name="DiscountBySubCategory",
        ),
    ]
