# Generated by Django 4.2.11 on 2024-04-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_discount_subcategories_delete_discountbysubcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
