# Generated by Django 4.2.11 on 2024-04-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_order_discount_order_grandtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
